# Generated by Django 4.0.2 on 2022-05-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=80)),
                ('email', models.EmailField(max_length=255)),
                ('title', models.TextField(max_length=255)),
                ('content', models.TextField(max_length=1000)),
                ('replyContent', models.TextField(max_length=1000)),
                ('sendDate', models.TextField(max_length=20)),
                ('sendForm', models.TextField(max_length=80)),
            ],
        ),
    ]
