# Generated by Django 4.0.2 on 2022-05-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='replyContent',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
